<?php

########################################################################
# Extension Manager/Repository config file for ext: "flexslider"
#
# Auto generated by Extension Builder 2012-04-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FlexSlider',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Andy Hausmann, Andreas Walter',
	'author_email' => 'hi@andy-hausmann.de, mail@andreas-walter.info',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.00',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>